import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

// import "./globals.css";
import ThemeRegistry from "../utils/ThemeRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
